name: "Apply Production"

on:
  workflow_dispatch:
    inputs:
      tf_function:
        type: string
        description: "plan or apply"

  # push:
  #   branches:
  #     - main

env:
  TERRAFORM_VERSION: 1.8.0
  TERRAGRUNT_VERSION: v0.37.1

jobs:
  terragrunt-apply-all-production:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/terragrunt
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      
      - name: Initialise tf for production
        run: |
          cd terragrunt/
          terragrunt run-all init --terragrunt-non-interactive

      - name: Production Deploy/Plan
        env:
          SLACK_WEBHOOK_URL : ${{ secrets.SLACK_WEBHOOK_URL}}
        run: |
          cd terragrunt/
          terragrunt run-all ${{inputs.tf_function}} --terragrunt-non-interactive